# Generated by Django 4.0.3 on 2022-03-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IllustratedGuide',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('monType', models.CharField(max_length=20)),
                ('height', models.CharField(blank=True, max_length=10, null=True)),
                ('weight', models.CharField(blank=True, max_length=10, null=True)),
                ('thumbnail', models.CharField(max_length=256)),
                ('fullImage', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
