# Generated by Django 4.0.3 on 2022-03-30 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('illustrated_guide', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='illustratedguide',
            old_name='fullImage',
            new_name='full_image',
        ),
        migrations.RenameField(
            model_name='illustratedguide',
            old_name='monType',
            new_name='mon_type',
        ),
    ]
